-- Perfume Store
-- Seed de desarrollo. Intencionalmente vacio de datos comerciales.
--
-- Este archivo contenia anteriormente el catalogo real de productos de
-- Pauli Store (dobladitas, quequitos) heredado de la copia inicial del
-- repositorio. Se neutralizo en la Fase 1A (fundacion de base de datos)
-- porque esta fase prohibe copiar productos, clientes, pedidos u otros
-- datos comerciales reales de Pauli Store.
--
-- El catalogo de perfumes (+100 productos, CSV masivo) se cargara en una
-- fase posterior mediante el importador que se defina para ese fin, no
-- mediante este archivo.
--
-- business_settings ya recibe su fila base (sin datos reales) desde
-- supabase/schema.sql / supabase/migrations/20260724000000_perfume_store_foundation.sql.
-- No es necesario repetirla aqui.
